version: "3.1"

services:
  promantis_postgres:
    container_name: promantis_postgres
    image: postgres:latest
    restart: always
    volumes:
      - pgdata_live:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: promantis
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: promantis

  promantis:
    container_name: promantis
    image: ghcr.io/sgpromantis/promantis:latest
    ports:
      - 1000:3000
      - 1001:5003
# If running via Docker on a hypervisor, enable DNS.
#    dns:
#      - 1.1.1.1
#      - 8.8.8.8
    restart: always
    depends_on:
      - promantis_postgres
    volumes:
      - promantis_uploads:/app/apps/api/uploads
    environment:
      DB_USERNAME: "promantis"
      DB_PASSWORD: "12345"
      DB_HOST: "promantis_postgres"
      SECRET: 'promantis4life'

volumes:
 pgdata_live:
 promantis_uploads:
