version: "3.1"

services:
  promantis_postgres:
    container_name: promantis_postgres
    image: postgres:latest
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: promantis
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: promantis

  promantis:
    container_name: promantis
    image: ghcr.io/sgpromantis/promantis:dev
    ports:
      - 3000:3000
      - 5003:5003
    restart: always
    depends_on:
      - promantis_postgres
    environment:
      DB_USERNAME: "promantis"
      DB_PASSWORD: "1234"
      DB_HOST: "promantis_postgres"
      SECRET: 'promantis4life'

volumes:
 pgdata: